version: "3.8"
services:
  source:
    build: .
    restart: no
    container_name: source
  resipient:
    image: nginx:latest
    restart: no
    volumes:
      - ./recipient/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    container_name: resipient
